spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://51.103.212.154:3306/bilbasen_db}

spring.datasource.username=${JDBC_USERNAME:root}
spring.datasource.password=${JDBC_PASSWORD:mypassword}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0